config/routes.rb
BlogPlay::Application.routes.draw do

  resources :blog_posts

  resources :users

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :title, :article, :author
  validates_presence_of :title  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :email, :first_name, :last_name
  validates_presence_of :password
  validates_presence_of :username
  validates_presence_of :email
  validates_uniqueness_of :email

  def name
    return "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.all
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  end

  def new 
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(params[:blog_post])
    if @blog_post.save
      redirect_to blog_posts_path
    else
      render "new"
    end
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path
    else 
      render "new"
    end
  end

  def index
    @users = User.all
  end
  
  def show
   @user = User.find_by_id params[:id] 
  end
  
  def edit
   @user = User.find_by_id params[:id] 
  end
  
  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'Successfully updated user'
      redirect_to users_path
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog_posts/index.html.haml
%h1
  Blog Post

%p
  Here is the list of all the Blog Posts

=@blog_posts.count
%table
  %tr
    %th Title
    %th Author
  -@blog_posts.each do |bp|
    %tr
      %td= link_to bp.title, blog_post_path(bp)
      %td= bp.author

%p
  =link_to "NEW", new_blog_post_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogPlay</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.haml
=form_for @user do |f|
  -if @user.errors.any?  #error_explanation
    %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg
  =f.label :username
  =f.text_field :username
  =f.label :password
  =f.text_field :password
  =f.label :email
  =f.text_field :email
  =f.label :first_name
  =f.text_field :first_name
  =f.label :last_name
  =f.text_field :last_name
  =f.submit 'Save'

app/views/users/edit.html.haml
%h1 Edit User
=render :partial => "form"

app/views/users/index.html.haml
%h1 Listed Users
=link_to "new", new_user_path
%br
-for user in @users
  = link_to user.username, user_path(user)
  = user.email
  %br

app/views/users/new.html.haml
%header
  %h2 New User

%section
  =render :partial => "form"

app/views/users/show.html.haml
%h1 User Profile
=link_to "edit", edit_user_path(@user)
=link_to "destroy", user_path(@user), :method => :delete, :confirm => true

=@user.username
=@user.email